AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0ff8a91507f77f867 
      UserData:
        "Fn::Base64":
          "Fn::Sub": |
            #!/bin/bash -xe
            yum update -y
            yum install docker -y
            service docker start 
            docker run -it --rm -d -p 80:80 --name web nginx
Outputs:
  URL:
    Description: Web URL
    Value: !GetAtt Ec2Instance.PublicDnsName
    Export:
      Name: !Sub URL
